### ISSUE TITLE
Impossible Active

### ISSUE THREAD

**Issue by filiperivelli** [ozpital/ozpital-wpwetransfer#1]
I received this return trying active:
`Catchable fatal error: Argument 1 passed to Ozpital\WPWeTransfer\Core\OWPWT_Option::register() must be an instance of Ozpital\WPWeTransfer\Core\String, string given, called in /home/filip518/public_html/site_teste/wp-content/plugins/ozpital-wetransfer/app/Core/OWPWT_Option.php on line 56 and defined in /home/filip518/public_html/site_teste/wp-content/plugins/ozpital-wetransfer/app/Core/OWPWT_Option.php on line 22`

**Comment by filiperivelli** [comment]
Hi,
I installed it  direct from the wordpress.
Thanks.
![wpwetransfer](https://user-images.githubusercontent.com/40794249/42227237-6afb9c96-7eb7-11e8-8355-b435cad1016d.png)

**Comment by ozpital** [comment]
Hi @filiperivelli - I've managed to reproduce the error by downgrading PHP from 7 to 5.5.9

Thanks for letting me know and I'll get this fixed this soon.

**Comment by ozpital** [comment]
Sorry @filiperivelli - Took a look this morning.
I'm using a feature of PHP7 'Type Declarations' throughout the script and don't want to revert.

Feel free to fork and amend the script to suit but I expect other PHP 7 features will need amending to suit your PHP version too.

For clarity I have updated the README.txt to indicate PHP 7 is now a minimum requirement.
